# Windows-Only Release Workflow
# This workflow builds and publishes Windows installers only
# Use this for testing and releases on Windows platform

name: "windows-release"

on:
  workflow_dispatch:
  push:
    branches:
      - release
    paths:
      - 'src-tauri/**'
      - 'src/**'
      - 'package.json'

jobs:
  publish-windows:
    permissions:
      contents: write
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Check Rust and Cargo versions
        run: |
          rustc --version
          cargo --version

      - name: List src-tauri directory
        run: Get-ChildItem -Path src-tauri -Force
        shell: pwsh

      - name: Install frontend dependencies
        run: pnpm i

      - name: Verify WebView2 Configuration
        shell: pwsh
        run: |
          Write-Host "================================" -ForegroundColor Cyan
          Write-Host "WebView2 Configuration Check" -ForegroundColor Cyan
          Write-Host "================================" -ForegroundColor Cyan
          $config = Get-Content src-tauri/tauri.conf.json | ConvertFrom-Json
          $installMode = $config.bundle.windows.webviewInstallMode.type
          $silentMode = $config.bundle.windows.webviewInstallMode.silent
          $nsisMode = $config.bundle.windows.nsis.installMode
          $languages = $config.bundle.windows.nsis.languages

          Write-Host "Install Mode: $installMode" -ForegroundColor Yellow
          Write-Host "Silent Mode: $silentMode" -ForegroundColor Yellow
          Write-Host "NSIS Mode: $nsisMode" -ForegroundColor Yellow
          Write-Host "Languages: $($languages -join ', ')" -ForegroundColor Yellow
          Write-Host "Allow Downgrades: $($config.bundle.windows.allowDowngrades)" -ForegroundColor Yellow

          if ($installMode -eq "downloadBootstrapper") {
            Write-Host "✓ WebView2 bootstrapper will be downloaded at install time" -ForegroundColor Green
            if ($silentMode -eq $false) {
              Write-Host "✓ WebView2 installation will be visible to user" -ForegroundColor Green
            }
          } else {
            Write-Host "⚠ Warning: Not using downloadBootstrapper" -ForegroundColor Yellow
          }

          if ($nsisMode -eq "perMachine") {
            Write-Host "✓ Using perMachine installation (recommended for Windows)" -ForegroundColor Green
          }
          Write-Host "================================" -ForegroundColor Cyan

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          # Force dynamic runtime linkage (/MD) to prevent conflicts
          RUSTFLAGS: "-Ctarget-feature=-crt-static"
          CFLAGS: "/MD /wd9025"
          CXXFLAGS: "/MD /wd9025"
        with:
          includeUpdaterJson: true
          tagName: v__VERSION__
          releaseName: "BEAR LLM AI v__VERSION__"
          releaseBody: |
            ## Windows Release v__VERSION__

            ### Installation
            - Download the `.exe` installer below
            - Run the installer (may require administrator privileges)
            - If WebView2 is not installed, you will see a separate WebView2 installation window
            - Wait for WebView2 installation to complete, then BEAR LLM AI installation will continue

            ### What's New
            - Version 0.0.13 release
            - Automated GitHub release with exe download support

            ### System Requirements
            - Windows 10 (1809+) or Windows 11
            - ~100MB disk space
            - Internet connection required during installation (for WebView2 download)

            ---

            🤖 Generated with [Claude Code](https://claude.com/claude-code)
          releaseDraft: false
          prerelease: false
          releaseCommitish: ${{ github.sha }}
          args: ""

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-installers
          path: |
            src-tauri/target/release/bundle/nsis/*.exe
            src-tauri/target/release/bundle/msi/*.msi
          retention-days: 7
